Sign In & Otp
aindrila-choudhuri/qur8-front-end pull request #3
Opened 2023-12-13 18:18 UTC by Bodhisatwa2002

Here the redux code is not yet finalised and there need to be canges that should be made as per signin screen

2023-12-20 07:25 UTC, aindrila-choudhuri requested changes
Have you implemented the component visibility based on isLoggedIn property?

2023-12-20 07:25 UTC, aindrila-choudhuri commented on constants/theme.js
> +const COLORS = {
Follow English spelling, not American :)

2023-12-20 07:25 UTC, aindrila-choudhuri commented on constants/theme.js
This file is good!

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/components/otp/Otp.jsx
remove commented file

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/components/signin/Signin.jsx
same

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/redux/slices/authSlices.js
> +      state.email = action.payload.email;
We need to store the phone number. 
and better code: const { username, phoneNumber } = action.payload;

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/redux/slices/authSlices.js
> +      state.userName = action.payload.userName;
this will be set true in signin, nothing to get from payload.

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/screens/otp.js
> +            <View style={styles.otpLayout} />
What are these?

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/screens/signin.jsx
> +  const [number, onChangeNumber] = React.useState("");
import useState.

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/screens/signin.jsx
> +  text3: {
what is the difference between text1 and text3?

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/screens/signin.jsx
> +  text4: {
No difference between text2 and text4. That's why I asked to use classes, so that it can be reused.

2023-12-20 07:25 UTC, aindrila-choudhuri commented on src/screens/signin.jsx
file extension should be js

2023-12-20 16:03 UTC, Bodhisatwa2002 commented on src/screens/signin.jsx
> +  text3: {
Changes done . Styled under 1 class

2023-12-20 16:03 UTC, Bodhisatwa2002 commented on src/screens/signin.jsx
> +  text4: {
Changes done . Styled under 1 class

2023-12-20 16:06 UTC, Bodhisatwa2002 commented on src/screens/signin.jsx
> +  const [number, onChangeNumber] = React.useState("");
Done

2023-12-20 16:07 UTC, Bodhisatwa2002 commented on src/screens/signin.jsx
Done

2023-12-20 16:39 UTC, Bodhisatwa2002 commented on src/redux/slices/authSlices.js
> +      state.email = action.payload.email;
Done

2023-12-20 16:39 UTC, Bodhisatwa2002 commented on src/redux/slices/authSlices.js
> +      state.userName = action.payload.userName;
Done

2023-12-20 16:40 UTC, Bodhisatwa2002 commented on src/components/otp/Otp.jsx
Done

2023-12-20 16:40 UTC, Bodhisatwa2002 commented on src/components/signin/Signin.jsx
Done

2023-12-21 08:43 UTC, Bodhisatwa2002 commented on src/screens/otp.js
> +            <View style={styles.otpLayout} />
This was basically images that i showed but now i improved it totally and made it text Input

2023-12-22 04:34 UTC, aindrila-choudhuri requested changes

2023-12-22 04:34 UTC, aindrila-choudhuri commented on assets/fonts/OFL.txt
is this file required?

2023-12-22 05:54 UTC, Bodhisatwa2002 commented on assets/fonts/OFL.txt
no, deleted this file and sended PR

2023-12-28 14:35 UTC, aindrila-choudhuri commented
Closing it, since new PR is created

2023-12-28 14:35 UTC, closed without merging